### ISSUE TITLE
SDK docs action no longer works

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/tableland-js#19]
**Describe the bug**
After converting to a monorepo the docs.yml workflow isn't working. 

**To Reproduce**
Look at the failed docs actions here: https://github.com/tablelandnetwork/tableland-js/actions/workflows/docs.yml

**Expected behavior**
Docs should be built

**Additional context**
It seems that the `pwd` of the build command being run is wrong.

**Comment by dtbuchholz** [comment]
(moved to #95 for linear syncing purposes)
