### ISSUE TITLE
Using this package to run tests with github actions is buggy

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/tableland-js#40]
### what happens
Running tests on a developer machine always works as expected, but when the tests are run as part of CI via github actions they fail about half the time.

### how to reproduce
For an Example look at: https://github.com/tablelandnetwork/jeti/actions/runs/5191892282/jobs/9360322039
You will see that the network logs are turned on and the tests start running before the Validator has created the healthbot table.  Some of the tests pass in this case, but the tests that create tables end up failing because the validator transaction receipt polling is aborted after the polling timeout is reached. 
As a means of exploring why this is happening I had the test setup wait for a full 60 seconds after the local-tableland network signaled that it is ready.  The same intermittent failures are still occurring.
I have a few theories why this is happening:
 - The Validator process is failing before the node.js process error listener has been attached correctly.
 - The Validator startup process is still taking place when the local-tableland parent process is signaling the network is ready.
 - The Validator is starting, but being overwhelmed with polling requests and smart contract events.

### What is expected
This package should work correctly for CI done via github actions

### Additional context
The parent process signals that the network is ready by inspecting the Validator process stdout, and waiting for a specific message.  That message is currently the string "processing height".  This is brittle at best, and we should consider having the Validator log a specific message when it considers itself to be fully online.

**Comment by dtbuchholz** [comment]
(moving to #96 for Linear syncing puropses)
