### ISSUE TITLE
[JST-11] SDK cannot be used with ethers.js v6

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/tableland-js#41]
## context

A user reported this bug in Discord here https://discord.com/channels/592843512312102924/1077277654132215960

## initial report

The initial report is from a user running the basic sdk example from the docs:

```typescript
import { Database, helpers } from "@tableland/sdk"
import { Wallet } from "ethers"
import * as dotenv from "dotenv"
dotenv.config()

async function main() {
    const privateKey: any = process.env.PRIVATE_KEY
    const rpc: any = process.env.RPC_URL
    
    const wallet = new Wallet(privateKey);
    const provider: any = helpers.getDefaultProvider(rpc)
    const signer: any = wallet.connect(provider);    
    interface Schema {
        id: number;
        name: string;
    }
    
    const db = new Database<Schema>({ signer: signer })
    
    const prefix: string = "my_sdk_table";
    
    const { meta: create } = await db
        .prepare(`CREATE TABLE ${prefix} (id integer primary key, name text);`)
        .run();
    
    console.log(create.txn?.name)
}

main();
```

This results in: `Error: RUN_ERROR: signer.getChainId is not a function`

## details

Ethers.js v6 was recently released https://docs.ethers.org/v6
With this release the signer interface no longer has the `getChainId` method.  The chainId is potentially available elsewhere within the ethers v6 signer, but we might want to decide if there's a more robust way to get the chainId.
The v3 SDK had the requirement that a specific network had been connected to, which made this problem a little easier.  

## ideas for a solution

- We could potentially try to sniff out what kind of interface the passed in signer supports.  The  downside I see here is that this could be cumbersome.
- We could determine the chainId from the query.  I _think_ this makes sense, but I'd have to dive into implementation to be sure.

<sub>[JST-11](https://linear.app/tableland/issue/JST-11/sdk-cannot-be-used-with-ethersjs-v6)</sub>

**Comment by dtbuchholz** [comment]
@joewagner i set up a Linear sync for `tableland-js` and recreated this issue from the Linear app so that it syncs to GH: https://github.com/tablelandnetwork/tableland-js/issues/77. before i go about doing this for the rest of the issues in this repo (i.e., those _not_ prefixed with `[TABJS-XX]`), i wanted to double check to make sure this is all okay to do.

also, i was wondering if any of the old issues in the Linear teams for `js-tableland`, `js-tableland-cli`, and `local-tableland` should be recreated in this repo? or, are those old project issues outdated and should _not_ be recreated in `tableland-js`? i can set them all up, just lmk.

**Comment by joewagner** [comment]
> @joewagner i set up a Linear sync for `tableland-js` and recreated this issue from the Linear app so that it syncs to GH: #77. before i go about doing this for the rest of the issues in this repo (i.e., those _not_ prefixed with `[TABJS-XX]`), i wanted to double check to make sure this is all okay to do.

That would be great!  You might be able to add the `linear` tag to an issue instead of re-creating, but I'm not soure on that.  If not then re-creating works for me.

> also, i was wondering if any of the old issues in the Linear teams for `js-tableland`, `js-tableland-cli`, and `local-tableland` should be recreated in this repo? or, are those old project issues outdated and should _not_ be recreated in `tableland-js`? i can set them all up, just lmk.

I Haven't looked recently. If there are any issues that still exist in the code and are listed in the old repos, you can use github's "transfer issue" feature to move them.  If for some reason that doesn't work re-creating them is ok with me.

Thanks again for dealing with this.

**Comment by dtbuchholz** [comment]
cool, sounds good, happy to help!
