### ISSUE TITLE
[JSTC-37] Create table help output shows prefix

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/tableland-js#87]
When creating a table, I noticed that the prefix is auto-applied from the table name in the create statement (neat!). However, the help command still shows that you can supply a prefix. I'm not sure if that still actually works. In either case, I don't think there should be two ways to do this… or if that is needed for some reason, the help command should be clear about it.

```
tableland create [schema] [prefix]        Create a new table
```

cc @carsonfarmer @joewagner 

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-37](https://linear.app/tableland/issue/JSTC-37/create-table-help-output-shows-prefix)</sub>

**Comment by dtbuchholz** [comment]
(moved to new issue #90)
