### ISSUE TITLE
[JSTC-17] Support smart SQL batching and import from SQL files

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/tableland-js#88]
**Is your feature request related to a problem? Please describe.**

- Writing many SQL statements from the command line right now is cumbersome, it would be great if we had a flag or other way to simply ingest SQL statements and push these to tableland
- Once we do support multiple statements at once, we'll need to have a nice way to batch and break these statements up into the right size for sending to the smart contract.
- Additionally, we should normalize the input statements so that they are more likely to succeed, using our custom parser

**Describe the solution you'd like**

Something like a --sql flag to would take a local SQL file, and normalize the statements, put them into appropriate sized batches, and then wait for confirmation to send.

**Describe alternatives you've considered**

Not waiting for confirmation would be ok too, but this feels safer for users. Ideally, you could actually use local files, or remote files, and the cli would just do the right thing.

<sub>[JSTC-17](https://linear.app/tableland/issue/JSTC-17/support-smart-sql-batching-and-import-from-sql-files)</sub>

**Comment by dtbuchholz** [comment]
(test comment from GH to see if things sync to linear for a transferred issue)
